[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['forge-std/=lib/forge-std/src/', 'openzeppelin-contracts/contracts/=lib/openzeppelin-contracts/contracts/']
solc_version = "0.8.15"
optimizer_runs = 200
gas_reports = ["AlchemixGovernor", "BaseGauge", "Bribe", "FluxToken", "Minter", "RevenueHandler", "RewardPoolManager", "RewardsDistributor", "Voter", "VotingEscrow"]

[rpc_endpoints]
sepolia = "${INFURA_API_KEY}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }