name: Forge Tests

on: [push, pull_request]

jobs:
    forge-tests:
        name: Runs foundry tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install Foundry
              uses: onbjerg/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Install dependencies
              run: forge install

            - name: Install submodules
              run: git submodule update --init --recursive

            - name: Run tests and coverage
              env:
                  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
                  TEST_PROFILE: default
              run: ./test.sh
